export const menu = [
  {
    id: "all-users",
    title: "allUsers",
    translate: "navigations.allUsers",
    type: "item",
    icon: "users",
    url: "dashboard/admin/all-users",
    users: ["admin"],
  },
  {
    id: "all-fishes",
    title: "allFishes",
    translate: "navigations.allFishes",
    type: "item",
    icon: "shield",
    url: "dashboard/admin/all-fishes",
    users: ["admin"],
  },
  {
    id: "age-of-fishes",
    title: "ageOfFishes",
    translate: "navigations.ageOfFishes",
    type: "item",
    icon: "calendar",
    url: "dashboard/admin/age-of-fishes",
    users: ["admin"],
  },
  {
    id: "all-origins",
    title: "allFishes",
    translate: "navigations.allOrigins",
    type: "item",
    icon: "file-text",
    url: "dashboard/admin/all-origins",
    users: ["admin"],
  },
  {
    id: "all-waters",
    title: "allWaters",
    translate: "navigations.allWaters",
    type: "item",
    icon: "droplet",
    url: "dashboard/admin/all-waters",
    users: ["admin"],
  },
  {
    id: "report-sales",
    title: "reportSales",
    translate: "navigations.reportSales",
    type: "item",
    icon: "droplet",
    url: "dashboard/owner/report-sales",
    users: ["owner"],
  },
];
