export const menu = [
  {
    id: "all-users",
    title: "allUsers",
    translate: "navigations.allUsers",
    type: "item",
    icon: "users",
    url: "dashboard/admin/all-users",
    users: ["admin"],
  },
  {
    id: "settings",
    title: "Settings",
    translate: "navigations.settings",
    type: "item",
    icon: "settings",
    url: "dashboard/admin/settings/booking-settings",
    users: ["admin"],
  },
  {
    id: "superadmin-all-users",
    title: "All users",
    translate: "navigations.allUsers",
    type: "item",
    icon: "user",
    url: "dashboard/superadmin/all-users",
    users: ["superadmin"],
  },
  {
    id: "sms-packages",
    title: "Sms packages",
    translate: "navigations.smsPackages",
    type: "item",
    icon: "package",
    url: "dashboard/superadmin/sms-packages",
    users: ["superadmin"],
  },
  {
    id: "gateway-country-prefix",
    title: "Gateway country prefix",
    translate: "navigations.gatewayCountryPrefix",
    type: "item",
    icon: "globe",
    url: "dashboard/superadmin/gateway-country-prefix",
    users: ["superadmin"],
  },
  {
    id: "licenses",
    title: "Licenses",
    translate: "navigations.licenses",
    type: "item",
    icon: "credit-card",
    url: "dashboard/superadmin/licenses",
    users: ["superadmin"],
  },
];
